export const ROSTER_LIST = {
    "ORC": "Orques",
    "MV": "Mort-Vivants",
    "AMA": "Amazones",
    "DW": "Nains",
    "EN": "Elfes Noirs",
    "BF": "Bas-Fonds",
    "NO": "Nordiques",
    "HU": "Humains",
    "NEC": "Necromantiques",
    "SKA": "Skavens",
    "HL": "Hommes-Lezards",
    "EDC": "Elus du Chaos",
    "REN": "Renegats du Chaos",
    "NUR": "Nurgle",
    "ON": "Orques Noirs",
    "GOB": "Gobelins",
    "HA": "Halfelins",
    "UE": "Union Elfique",
    "WE": "Elfes Sylvains",
    "NOB": "Noblesse Imperiale",
    "OWA": "Alliance du Vieux Monde",
    "KHO": "Khornes",
    "VAM": "Vampires",
    "TBD": "A determiner",
}

export const ROSTER_BY_COACH = {
    "Nîme l'Ancien": ROSTER_LIST.VAM,
    "LePiotr": ROSTER_LIST.KHO,
    "Kanwulf": ROSTER_LIST.ORC,
    "Grimdark": ROSTER_LIST.HL,
    "Silsei": ROSTER_LIST.VAM,
    "Kos": ROSTER_LIST.HU,
    "Papatte": ROSTER_LIST.VAM,
    "Petit lutin": ROSTER_LIST.VAM,
    "jojolafrite": ROSTER_LIST.VAM,
    "Wilhelm": ROSTER_LIST.ORC,
    "Blackweasel": ROSTER_LIST.AMA,
    "Lao Jia": ROSTER_LIST.MV,
    "Otopous": ROSTER_LIST.VAM,
    "Momolskyy": ROSTER_LIST.AMA,
    "Prysm": ROSTER_LIST.ORC,
    "Cahinn": ROSTER_LIST.UE,
    "Captain Blind": ROSTER_LIST.KHO,
    "Pifou": ROSTER_LIST.EDC,
    "Rob-inet": ROSTER_LIST.NOB,
    "Ouarzy": ROSTER_LIST.SKA,
    "Jibz74": ROSTER_LIST.UE,
    "Rookiz": ROSTER_LIST.VAM,
    "Sethi": ROSTER_LIST.REN,
    "Némésis": ROSTER_LIST.DW,
    "frd": ROSTER_LIST.WE,
    "Akol": ROSTER_LIST.AMA,
    "Yaouch": ROSTER_LIST.KHO,
    "Grumly": ROSTER_LIST.VAM,
    "Moby": ROSTER_LIST.EN,
    "Shkeil": ROSTER_LIST.ON,
    "Dzerko12": ROSTER_LIST.EN,
    "Nainvert": ROSTER_LIST.KHO,
    "Boyfutur": ROSTER_LIST.WE,
    "Rascal 1er": ROSTER_LIST.SKA,
    "Thulsa Doom": ROSTER_LIST.NUR,
    "Mifune38": ROSTER_LIST.MV,
    "Lemarseillais": ROSTER_LIST.VAM,
    "Mellenor": ROSTER_LIST.EDC,
    "Nourrou": ROSTER_LIST.EN,
    "Castor": ROSTER_LIST.HU,
    "Ours": ROSTER_LIST.WE,
    "Grimgor": ROSTER_LIST.ON,
    "LoKKhaR": ROSTER_LIST.REN,
    "Ysiel": ROSTER_LIST.HU,
    "Pinguins": ROSTER_LIST.VAM,
    "Démosthène": ROSTER_LIST.HUM,
    "Bartabaf": ROSTER_LIST.AMA,
    "Paladin": ROSTER_LIST.VAM,
    "Seb27": ROSTER_LIST.ORC,
    "LPOW06": ROSTER_LIST.NEC,
}